export type CapabilityKind = "tool" | "software" | "connector" | "knowledge" | "runtime" | "report"
export type ProvisioningState = "healthy" | "configured" | "planned" | "degraded" | "unavailable"

export type CapabilityCatalogEntry = {
  id: string
  name: string
  kind: CapabilityKind
  provider: string
  state: ProvisioningState
  organizationWide: boolean
  permissionPolicy: "owner-managed" | "scoped-read" | "department-use"
  departmentIds: string[]
  description: string
  evidence: string
  iconSlug?: string
}

const allDepartments = ["marketing", "engineering", "operations", "knowledge"]

export const capabilityCatalog: CapabilityCatalogEntry[] = [
  // Core & Knowledge
  {
    id: "rheos-brain",
    name: "Rheos Brain (Local Vault & MCP)",
    kind: "knowledge",
    provider: "rbrain / Local Vault v2",
    state: "healthy",
    organizationWide: true,
    permissionPolicy: "scoped-read",
    departmentIds: allDepartments,
    description: "Permission-scoped search, read, chunk and citation access over Rheos Brain vault roots.",
    evidence: "52 project hubs, 13 practices, 79 sessions active.",
    iconSlug: "brain",
  },
  {
    id: "buzz-local",
    name: "Buzz Workspace Layer",
    kind: "connector",
    provider: "Buzz Desktop",
    state: "healthy",
    organizationWide: true,
    permissionPolicy: "owner-managed",
    departmentIds: allDepartments,
    description: "Multi-agent coordination, messaging channels, agent teams, and shared nest.",
    evidence: "Buzz Desktop active on macOS.",
    iconSlug: "buzz",
  },
  {
    id: "composio",
    name: "Composio Tool Hub",
    kind: "software",
    provider: "Composio CLI / MCP",
    state: "healthy",
    organizationWide: true,
    permissionPolicy: "owner-managed",
    departmentIds: allDepartments,
    description: "26 toolkits (22 active) managing external authentication, token refresh and tool execution.",
    evidence: "Composio CLI active with verified workspace auth (archie@rheos.app).",
    iconSlug: "composio",
  },
  {
    id: "tinyfish",
    name: "TinyFish Web Primitives",
    kind: "tool",
    provider: "TinyFish CLI / MCP",
    state: "healthy",
    organizationWide: true,
    permissionPolicy: "department-use",
    departmentIds: allDepartments,
    description: "Search, fetch and agent browser automation installed across all harnesses.",
    evidence: "TinyFish MCP active across 5 agent harnesses.",
    iconSlug: "tinyfish",
  },

  // Engineering Tools
  {
    id: "firebase-platform",
    name: "Firebase Platform (Firestore & Functions)",
    kind: "connector",
    provider: "Firebase MCP / CLI",
    state: "healthy",
    organizationWide: false,
    permissionPolicy: "owner-managed",
    departmentIds: ["engineering", "operations"],
    description: "Firestore database, Cloud Functions triggers and emulators for local rig verification.",
    evidence: "Connected across local rig and production cloud environment.",
    iconSlug: "firebase",
  },
  {
    id: "linear",
    name: "Linear",
    kind: "connector",
    provider: "Composio Linear Toolkit",
    state: "healthy",
    organizationWide: false,
    permissionPolicy: "department-use",
    departmentIds: ["engineering", "operations"],
    description: "Sprint issues, project roadmaps, and cycle management.",
    evidence: "Composio Linear toolkit connected.",
    iconSlug: "linear",
  },
  {
    id: "local-rig-worker",
    name: "Local Dev Rig & Emulators",
    kind: "runtime",
    provider: "rheos-rig MCP",
    state: "healthy",
    organizationWide: false,
    permissionPolicy: "department-use",
    departmentIds: ["engineering", "knowledge"],
    description: "Safe dev server execution, Firebase local emulators, port management and test harness.",
    evidence: "Rig runtime running with isolated port and process supervisor.",
    iconSlug: "rig",
  },
  {
    id: "firefox-devtools",
    name: "Firefox DevTools (Browser QA)",
    kind: "tool",
    provider: "Firefox DevTools Protocol",
    state: "healthy",
    organizationWide: false,
    permissionPolicy: "department-use",
    departmentIds: ["engineering", "knowledge"],
    description: "Browser automation and UI visual QA verification against local rigs.",
    evidence: "Firefox headless devtools socket accessible.",
    iconSlug: "firefox",
  },
  {
    id: "sentry",
    name: "Sentry Crash Triage",
    kind: "connector",
    provider: "Sentry MCP / Composio",
    state: "configured",
    organizationWide: false,
    permissionPolicy: "scoped-read",
    departmentIds: ["engineering"],
    description: "Breadcrumb-first exception analysis and production error logs.",
    evidence: "Sentry toolkit configured; org slug reconnection queued.",
    iconSlug: "sentry",
  },
  {
    id: "vercel",
    name: "Vercel Deployments",
    kind: "connector",
    provider: "Vercel MCP / CLI",
    state: "healthy",
    organizationWide: false,
    permissionPolicy: "owner-managed",
    departmentIds: ["engineering"],
    description: "Frontend preview deployments and web dashboard hosting.",
    evidence: "Production deployment pipeline connected.",
    iconSlug: "vercel",
  },
  {
    id: "stripe",
    name: "Stripe Billing & Customers",
    kind: "connector",
    provider: "Stripe MCP",
    state: "healthy",
    organizationWide: false,
    permissionPolicy: "department-use",
    departmentIds: ["engineering", "operations"],
    description: "Customer subscription status, checkout sessions and billing invoices.",
    evidence: "Stripe integration active.",
    iconSlug: "stripe",
  },
  {
    id: "shadcn-remotion",
    name: "UI Kit & Remotion Docs",
    kind: "knowledge",
    provider: "Rheos Design / Docs",
    state: "configured",
    organizationWide: false,
    permissionPolicy: "scoped-read",
    departmentIds: ["engineering"],
    description: "Shadcn component references and Remotion video rendering best practices.",
    evidence: "UI kit documentation available.",
    iconSlug: "react",
  },

  // Growth & Marketing Tools
  {
    id: "google-search-console",
    name: "Google Search Console",
    kind: "connector",
    provider: "Composio GSC Toolkit",
    state: "healthy",
    organizationWide: false,
    permissionPolicy: "scoped-read",
    departmentIds: ["marketing"],
    description: "Search impressions, clicks, keyword rank and indexing performance.",
    evidence: "Connected via Composio 19 Aug across all harnesses.",
    iconSlug: "gsc",
  },
  {
    id: "bing-webmaster",
    name: "Bing Webmaster Tools",
    kind: "connector",
    provider: "Composio Bing Toolkit",
    state: "healthy",
    organizationWide: false,
    permissionPolicy: "scoped-read",
    departmentIds: ["marketing"],
    description: "Bing search indexing, crawl queries and SEO diagnostics.",
    evidence: "Connected via Composio 19 Aug.",
    iconSlug: "bing",
  },
  {
    id: "google-analytics",
    name: "Google Analytics 4",
    kind: "connector",
    provider: "Composio GA4 Toolkit",
    state: "healthy",
    organizationWide: false,
    permissionPolicy: "scoped-read",
    departmentIds: ["marketing"],
    description: "Traffic channels, engagement duration and conversion funnels.",
    evidence: "GA4 connected via Composio.",
    iconSlug: "ga4",
  },
  {
    id: "amplitude-analytics",
    name: "Amplitude Analytics",
    kind: "connector",
    provider: "Amplitude MCP",
    state: "configured",
    organizationWide: false,
    permissionPolicy: "scoped-read",
    departmentIds: ["marketing"],
    description: "User journey funnels and AI-crawler visit tracking.",
    evidence: "Amplitude MCP registered.",
    iconSlug: "amplitude",
  },
  {
    id: "firecrawl",
    name: "Firecrawl Web Scraper",
    kind: "tool",
    provider: "Composio Firecrawl",
    state: "healthy",
    organizationWide: false,
    permissionPolicy: "department-use",
    departmentIds: ["marketing"],
    description: "Deep research scraping and structured markdown web extraction.",
    evidence: "Firecrawl actions available in Composio cache.",
    iconSlug: "firecrawl",
  },
  {
    id: "paper",
    name: "Paper Design Canvas",
    kind: "software",
    provider: "Paper App",
    state: "healthy",
    organizationWide: false,
    permissionPolicy: "department-use",
    departmentIds: ["marketing"],
    description: "Design canvas, artboard layout and visual asset authoring.",
    evidence: "Paper comments & export workflow active.",
    iconSlug: "paper",
  },
  {
    id: "eden",
    name: "Eden Social Scheduler",
    kind: "software",
    provider: "Eden App",
    state: "healthy",
    organizationWide: false,
    permissionPolicy: "department-use",
    departmentIds: ["marketing"],
    description: "Social media calendar scheduling and multi-platform publishing.",
    evidence: "Eden app installed on machine.",
    iconSlug: "eden",
  },
  {
    id: "apollo-prospecting",
    name: "Apollo Prospecting",
    kind: "connector",
    provider: "Composio Apollo Toolkit",
    state: "configured",
    organizationWide: false,
    permissionPolicy: "department-use",
    departmentIds: ["marketing"],
    description: "B2B lead prospecting, contact search and org enrichment.",
    evidence: "Composio toolkit present; account linking pending.",
    iconSlug: "apollo",
  },
  {
    id: "resend-email",
    name: "Resend Email",
    kind: "connector",
    provider: "Composio Resend Toolkit",
    state: "configured",
    organizationWide: false,
    permissionPolicy: "owner-managed",
    departmentIds: ["marketing"],
    description: "Transactional campaign and outreach email delivery.",
    evidence: "Composio toolkit present; sender domain verification pending.",
    iconSlug: "resend",
  },
  {
    id: "reddit-listening",
    name: "Reddit Social Listening",
    kind: "connector",
    provider: "Composio Reddit Toolkit",
    state: "healthy",
    organizationWide: false,
    permissionPolicy: "scoped-read",
    departmentIds: ["marketing"],
    description: "Subreddit thread monitoring, opportunity detection and sentiment scanning.",
    evidence: "Reddit search actions cached in Composio.",
    iconSlug: "reddit",
  },

  // Operations & Finance Tools
  {
    id: "starling-bank",
    name: "Starling Bank API",
    kind: "connector",
    provider: "Starling / GSM",
    state: "healthy",
    organizationWide: false,
    permissionPolicy: "scoped-read",
    departmentIds: ["operations"],
    description: "Accounting system of record, cash flow and daily statement sync (financeDailyCron).",
    evidence: "financeDailyCron active in backend prod since 24 Jun; token in Google Secrets Manager.",
    iconSlug: "starling",
  },
  {
    id: "attio-crm",
    name: "Attio CRM",
    kind: "connector",
    provider: "Composio Attio Toolkit",
    state: "healthy",
    organizationWide: false,
    permissionPolicy: "department-use",
    departmentIds: ["operations"],
    description: "Deals, contacts, company CRM records and sales pipeline.",
    evidence: "Attio toolkit connected in Composio.",
    iconSlug: "attio",
  },
  {
    id: "slack-comms",
    name: "Slack & Comms",
    kind: "connector",
    provider: "Composio Slack Toolkit",
    state: "healthy",
    organizationWide: false,
    permissionPolicy: "department-use",
    departmentIds: ["operations"],
    description: "Team notifications, operational alerts and channel messaging.",
    evidence: "Slack actions cached in Composio.",
    iconSlug: "slack",
  },
  {
    id: "gmail-drafts",
    name: "Gmail Drafts & Inbox",
    kind: "connector",
    provider: "Composio Gmail Toolkit",
    state: "healthy",
    organizationWide: false,
    permissionPolicy: "owner-managed",
    departmentIds: ["operations"],
    description: "Search workspace email threads and draft customer communications.",
    evidence: "Gmail toolkit connected in Composio.",
    iconSlug: "gmail",
  },

  // System & Infrastructure
  {
    id: "google-secrets-manager",
    name: "Google Secrets Manager",
    kind: "connector",
    provider: "GCP Secrets Manager",
    state: "healthy",
    organizationWide: false,
    permissionPolicy: "owner-managed",
    departmentIds: ["knowledge"],
    description: "75 managed production credentials (Starling, Attio, Azure, ElevenLabs, etc.).",
    evidence: "Cleaned and verified 19 Aug in rheoswebapp.",
    iconSlug: "gcp",
  },
  {
    id: "observability",
    name: "Google Cloud Observability & Logs",
    kind: "connector",
    provider: "gcloud / GCP Monitoring",
    state: "healthy",
    organizationWide: false,
    permissionPolicy: "scoped-read",
    departmentIds: ["knowledge"],
    description: "Cloud function logs, trace metrics, uptime health and incident alarms.",
    evidence: "gcloud logging and monitoring access active.",
    iconSlug: "gcloud",
  },

  // Investment Team Tools (ALDR Ltd)
  {
    id: "xero",
    name: "Xero Accounting API",
    kind: "connector",
    provider: "Composio / Xero",
    state: "healthy",
    organizationWide: false,
    permissionPolicy: "department-use",
    departmentIds: ["financial-modeling", "operations"],
    description: "Financial ledger, invoices, balance sheet & cashflow statement sync.",
    evidence: "Connected via Composio Xero integration.",
    iconSlug: "xero",
  },
  {
    id: "crunchbase-intel",
    name: "Crunchbase & Funding Data",
    kind: "connector",
    provider: "Composio / Crunchbase",
    state: "healthy",
    organizationWide: false,
    permissionPolicy: "scoped-read",
    departmentIds: ["investment-committee", "deal-sourcing"],
    description: "Company funding rounds, investor syndicates, valuation history & key personnel.",
    evidence: "Crunchbase API active via Composio.",
    iconSlug: "apollo",
  },
  {
    id: "pitchbook-dealroom",
    name: "PitchBook & Dealroom Sourcing",
    kind: "tool",
    provider: "TinyFish Web Primitives",
    state: "healthy",
    organizationWide: false,
    permissionPolicy: "department-use",
    departmentIds: ["investment-committee", "deal-sourcing"],
    description: "Venture deals, private equity transactions, emerging market trends & investor intelligence.",
    evidence: "TinyFish web agents connected to Dealroom & PitchBook.",
    iconSlug: "firecrawl",
  },
]
