export type CapabilityKind = "tool" | "software" | "connector" | "knowledge" | "runtime" | "report"
export type ProvisioningState = "healthy" | "configured" | "planned" | "degraded" | "unavailable"

export type CapabilityCatalogEntry = {
  id: string
  name: string
  kind: CapabilityKind
  provider: string
  state: ProvisioningState
  organizationWide: boolean
  permissionPolicy: "owner-managed" | "scoped-read" | "department-use"
  departmentIds: string[]
  description: string
  evidence: string
}

const allDepartments = ["leadership", "marketing", "operations", "engineering", "knowledge", "data-centre"]

export const capabilityCatalog: CapabilityCatalogEntry[] = [
  {
    id: "buzz-local",
    name: "Buzz local workspace",
    kind: "connector",
    provider: "Buzz Desktop 0.5.8",
    state: "configured",
    organizationWide: true,
    permissionPolicy: "owner-managed",
    departmentIds: allDepartments,
    description: "Communication, teams, identities and owner-reviewed agent lifecycle for the local organization pilot.",
    evidence: "Safe local adapter reads allowlisted fields; live state is derived from adapter health.",
  },
  {
    id: "linear",
    name: "Linear",
    kind: "connector",
    provider: "Linear MCP",
    state: "configured",
    organizationWide: false,
    permissionPolicy: "department-use",
    departmentIds: ["engineering"],
    description: "Direct coding-delivery access for Engineering; Linear remains canonical work state, while non-engineering writes stay manager- or member-granted.",
    evidence: "The current Hermes Linear MCP is live; default department access is Engineering-only and additional roles require explicit grants.",
  },
  {
    id: "composio",
    name: "Composio tool router",
    kind: "software",
    provider: "Composio CLI 0.2.31",
    state: "planned",
    organizationWide: false,
    permissionPolicy: "owner-managed",
    departmentIds: ["leadership", "marketing", "operations", "engineering"],
    description: "Owner connection and routing layer for approved external MCP/toolkit adapters; specific department operations remain separately health-gated.",
    evidence: "CLI is installed and authenticated to the owner workspace; a generic Composio executor is not granted directly to Buzz agents.",
  },
  {
    id: "reddit-listening",
    name: "Reddit opportunity finder",
    kind: "connector",
    provider: "Composio Reddit toolkit",
    state: "planned",
    organizationWide: false,
    permissionPolicy: "scoped-read",
    departmentIds: ["marketing"],
    description: "Find relevant Reddit discussions, inspect community rules and thread context, then prepare value-first reply drafts for owner review.",
    evidence: "Reddit MCP/tool schemas were discovered through Composio, but no connected Reddit account or session-bound Agent Tower wrapper is currently available; posting is prohibited.",
  },
  {
    id: "attio-crm",
    name: "Attio CRM",
    kind: "connector",
    provider: "Composio Attio toolkit",
    state: "planned",
    organizationWide: false,
    permissionPolicy: "department-use",
    departmentIds: ["marketing"],
    description: "Sales and marketing CRM access for people, companies and deals, initially read/search plus owner-reviewed upsert.",
    evidence: "The owner Composio workspace and Attio toolkit are connected; the bounded session-aware Buzz runtime wrapper is not implemented yet.",
  },
  {
    id: "apollo-prospecting",
    name: "Apollo prospecting",
    kind: "connector",
    provider: "Composio Apollo toolkit",
    state: "planned",
    organizationWide: false,
    permissionPolicy: "department-use",
    departmentIds: ["marketing"],
    description: "Prospect and organization search for the sales function inside Marketing, with enrichment and CRM writes separately gated.",
    evidence: "Apollo tools are present in the Composio catalogue but no connected Apollo account was reported by the latest safe discovery.",
  },
  {
    id: "gmail-drafts",
    name: "Gmail drafts",
    kind: "connector",
    provider: "Composio Gmail toolkit",
    state: "planned",
    organizationWide: false,
    permissionPolicy: "owner-managed",
    departmentIds: ["marketing"],
    description: "Marketing email search and draft creation; sending remains an explicit owner approval action while deliverability is unresolved.",
    evidence: "The Gmail toolkit is connected in Composio and draft schemas are available; the previous local gws CLI is absent and no Buzz wrapper is live.",
  },
  {
    id: "resend-email",
    name: "Resend email",
    kind: "connector",
    provider: "Composio Resend toolkit",
    state: "planned",
    organizationWide: false,
    permissionPolicy: "owner-managed",
    departmentIds: ["marketing"],
    description: "Transactional or campaign email alternative after domain/sender verification and a deliverability decision.",
    evidence: "Resend tools are present in the Composio catalogue, but no connected Resend account or verified sending domain was established.",
  },
  {
    id: "amplitude-analytics",
    name: "Amplitude analytics",
    kind: "connector",
    provider: "Amplitude MCP",
    state: "planned",
    organizationWide: false,
    permissionPolicy: "scoped-read",
    departmentIds: ["leadership", "marketing"],
    description: "Read-only product, funnel and AI-crawler analytics for marketing and leadership reporting.",
    evidence: "The Claude Code user MCP is connected; a local session-bound adapter for Buzz/Hermes agent identities is still required.",
  },
  {
    id: "search-console",
    name: "Search Console",
    kind: "connector",
    provider: "search-console-mcp",
    state: "planned",
    organizationWide: false,
    permissionPolicy: "scoped-read",
    departmentIds: ["marketing"],
    description: "Search performance, indexing and SEO evidence for Marketing; mutation and indexing submissions require separate approval.",
    evidence: "The Claude Code user MCP is connected; it is not yet exposed through the Agent Tower session-bound MCP.",
  },
  {
    id: "rheos-visibility-report",
    name: "Rheos Visibility report",
    kind: "report",
    provider: "rheos-visibility",
    state: "configured",
    organizationWide: false,
    permissionPolicy: "scoped-read",
    departmentIds: ["leadership", "marketing"],
    description: "A governed report surface assembled from visibility and analytics evidence; it is not a callable runtime tool.",
    evidence: "The Rheos repository identifies rheos-visibility as the internal GEO interface; report generation and freshness still need a dedicated adapter receipt.",
  },
  {
    id: "rheos-brain",
    name: "Rheos Brain local vault",
    kind: "knowledge",
    provider: "Local vault contract v2",
    state: "healthy",
    organizationWide: true,
    permissionPolicy: "scoped-read",
    departmentIds: allDepartments,
    description: "Permission-scoped search, read, chunk and citation access over approved local Brain roots.",
    evidence: "The local vault and contract are readable; the adapter allowlists Markdown under configured roots and returns exact versions/chunks.",
  },
  {
    id: "rheos-vault",
    name: "Rheos Vault",
    kind: "knowledge",
    provider: "Rheos MCP",
    state: "unavailable",
    organizationWide: false,
    permissionPolicy: "scoped-read",
    departmentIds: ["knowledge"],
    description: "Permission-scoped search, read and citation access for organizational knowledge.",
    evidence: "Latest verified MCP probe returned `Connection closed`; unrestricted fallback is prohibited.",
  },
  {
    id: "hermes-runtime",
    name: "Hermes Agent runtime",
    kind: "runtime",
    provider: "Hermes Agent",
    state: "configured",
    organizationWide: false,
    permissionPolicy: "owner-managed",
    departmentIds: ["leadership", "operations", "engineering", "data-centre"],
    description: "Model-agnostic orchestration, tools, sessions, skills, memory and multi-surface execution.",
    evidence: "Current Agent Tower control session is running through Hermes; per-role provisioning remains planned.",
  },
  {
    id: "claude-code-acp",
    name: "Claude Code ACP",
    kind: "runtime",
    provider: "Claude Code 2.1.226",
    state: "configured",
    organizationWide: false,
    permissionPolicy: "department-use",
    departmentIds: ["engineering"],
    description: "Engineering implementation runtime for Fable and Opus role lanes.",
    evidence: "Local CLI and Fable/Opus aliases were verified; Buzz persona linkage is not yet complete.",
  },
  {
    id: "browser-qa",
    name: "Browser QA",
    kind: "tool",
    provider: "Firefox DevTools / browser automation",
    state: "configured",
    organizationWide: false,
    permissionPolicy: "department-use",
    departmentIds: ["marketing", "engineering"],
    description: "Responsive visual, accessibility, console and interaction verification for web surfaces.",
    evidence: "Used to verify `/organization` desktop/mobile modal behavior and console state.",
  },
  {
    id: "firebase-platform",
    name: "Firebase platform",
    kind: "connector",
    provider: "Firebase MCP / CLI",
    state: "planned",
    organizationWide: false,
    permissionPolicy: "owner-managed",
    departmentIds: ["operations", "engineering", "data-centre"],
    description: "Project-scoped Firebase inspection and governed deploy/runtime operations.",
    evidence: "Firebase MCP is connected in Claude Code and project-scoped configs exist; no department-bound Buzz wrapper is live.",
  },
  {
    id: "observability",
    name: "Observability",
    kind: "connector",
    provider: "Google Cloud Observability MCP",
    state: "planned",
    organizationWide: false,
    permissionPolicy: "scoped-read",
    departmentIds: ["operations", "engineering", "data-centre"],
    description: "Logs, alerts, traces and runtime-health evidence for operations, engineering and infrastructure roles.",
    evidence: "A project-scoped Claude MCP registration exists; session-bound Agent Tower delivery and live health have not been verified.",
  },
  {
    id: "blender",
    name: "Blender",
    kind: "software",
    provider: "Blender desktop",
    state: "planned",
    organizationWide: false,
    permissionPolicy: "department-use",
    departmentIds: ["engineering"],
    description: "Approved source-asset production for the later Blender Asset Production stage.",
    evidence: "Application is installed; production asset work remains gated by spatial skin and brand approval.",
  },
  {
    id: "local-rig-worker",
    name: "Local Rig shared worker",
    kind: "runtime",
    provider: "Local Rig",
    state: "configured",
    organizationWide: false,
    permissionPolicy: "owner-managed",
    departmentIds: ["operations", "engineering", "data-centre"],
    description: "Bounded local worker jobs share the Rig-managed Muse process, one request slot and loopback OpenAI endpoint.",
    evidence: "Muse Glimmer artifacts/runtime and the loopback endpoint were verified previously; live availability is derived from the current redacted Rig snapshot and health probe.",
  },
  {
    id: "web-research",
    name: "Web research",
    kind: "tool",
    provider: "Approved search/read tools",
    state: "configured",
    organizationWide: true,
    permissionPolicy: "scoped-read",
    departmentIds: ["leadership", "marketing", "operations", "engineering", "knowledge"],
    description: "Bounded web search and source reading with citations where supported.",
    evidence: "Availability is runtime- and panel-specific; write/publish capabilities are not implied.",
  },
]
